## Test

In [433]:
print("hello world")

hello world

## Importing libs & data

In [434]:
import pandas as pd

In [435]:
dataset = pd.read_csv("../../data/messy_ml_data.csv")
dataset.head(3)

,PassengerId,Age,Fare,Gender,City,Subscription,Score,JoinDate,Email,Phone,IsActive,Remarks,DeptCode,DiscountCode
0,1,52.0,104.22,F,Tokyo,Free,55.0,2020-01-01,NaN,+1-555-8540,True,Good,D04,NaN
1,2,15.0,30.03,F,London,Premium,82.0,2020-01-02,user1@example.com,+1-555-6340,False,Average,D04,NaN
2,3,72.0,92.78,Female,New York,Basic,90.0,2020-01-03,user2@example.com,+1-555-3474,0,Poor,D02,SAVE10

### Fixing existing values in categorical data

In [436]:
print(dataset['Gender'].unique())

<StringArray>
['F', 'Female', 'Male', 'M', 'male', 'female', nan]
Length: 7, dtype: str

In [437]:
print(dataset['IsActive'].unique())

<StringArray>
['True', 'False', '0', 'Yes', '1', 'No', 'none', nan]
Length: 8, dtype: str

In [438]:
gender_map = {
    'F': 'Female',
    'female': 'Female',
    'M': 'Male',
    'male': 'Male'
}

In [439]:
isActive_map = {
    '0': 'False',
    'No': 'False',
    'none': 'False',
    '1': 'True',
    'Yes': 'True'
}

In [440]:
dataset['Gender'] = dataset['Gender'].replace(gender_map)

In [441]:
dataset['IsActive'] = dataset['IsActive'].replace(isActive_map)

In [442]:
dataset.isnull().sum()

PassengerId       0
Age              16
Fare             25
Gender           23
City             21
Subscription     26
Score            16
JoinDate         20
Email            12
Phone            26
IsActive         21
Remarks          26
DeptCode         21
DiscountCode    462
dtype: int64

In [443]:
dataset[dataset["Gender"].isnull()]
genderNullRows = dataset[dataset["Gender"].isnull()].index.tolist()

In [444]:
dataset[dataset["IsActive"].isnull()]

,PassengerId,Age,Fare,Gender,City,Subscription,Score,JoinDate,Email,Phone,IsActive,Remarks,DeptCode,DiscountCode
24,25,59.0,191.53,Female,Tokyo,Basic,49.0,2020-01-25,user24@example.com,+1-555-3194,NaN,ok,D02,NaN
31,32,47.0,133.69,Female,Tokyo,Free,61.0,2020-02-01,user31@example.com,+1-555-8344,NaN,Average,D01,SAVE20
38,39,7.0,270.98,Female,Berlin,FREE,47.0,01/01/2020,user38@example.com,+1-555-3398,NaN,Unknown,D01,SAVE20
67,68,18.0,84.90,Female,New York,Basic,81.0,2020-03-08,user67@example.com,+1-555-9648,NaN,Average,D04,SAVE20
70,71,74.0,101.42,Female,London,NaN,71.0,2020-03-11,user70@example.com,+1-555-5512,NaN,Good,D01,SAVE10
114,115,44.0,241.07,Male,Paris,Basic,63.0,2020-04-24,user114@example.com,+1-555-5860,NaN,Average,D02,WELCOME50
152,153,84.0,67.28,Male,Paris,Free,71.0,2020-06-01,user152@example.com,+1-555-9916,NaN,Poor,D04,SAVE10
209,210,70.0,463.53,Male,Paris,NaN,74.0,2020-07-28,user209@example.com,+1-555-2552,NaN,Excellent,D01,SAVE20
301,302,17.0,51.90,Female,Tokyo,Basic,70.0,2020-10-28,user301@example.com,+1-555-8260,NaN,Unknown,D02,WELCOME50
316,317,25.0,280.50,Female,Berlin,Premium,54.0,2020-11-12,user316@example.com,+1-555-3082,NaN,ok,D01,NaN
372,373,60.0,335.20,NaN,Tokyo,Basic,75.0,2021-01-07,user372@example.com,+1-555-8562,NaN,ok,D02,NaN
374,375,68.0,368.96,Male,New York,Free,68.0,2021-01-09,user374@example.com,+1-555-1790,NaN,Unknown,D03,SAVE10
431,432,69.0,NaN,Male,Paris,Basic,67.0,2021-03-07,user431@example.com,+1-555-6846,NaN,ok,D04,WELCOME50
489,490,23.0,91.85,Female,New York,Premium,74.0,2021-05-04,user489@example.com,+1-555-3830,NaN,Good,D02,NaN
524,525,35.0,432.44,Male,Tokyo,Premium,84.0,2021-06-08,user524@example.com,+1-555-9635,NaN,Average,D04,NaN
526,527,18.0,331.07,Female,Berlin,NONE,77.0,2021-06-10,user526@example.com,+1-555-5498,NaN,Good,D01,SAVE20
539,540,27.0,252.62,Female,New York,Premium,86.0,2021-06-23,user539@example.com,+1-555-7381,NaN,Unknown,D03,NaN
545,546,NaN,287.21,Female,Tokyo,Basic,81.0,2021-06-29,user545@example.com,+1-555-9858,NaN,Good,D03,SAVE10
610,611,76.0,144.08,Female,Tokyo,Basic,63.0,2021-09-02,user610@example.com,+1-555-6175,NaN,Poor,D04,WELCOME50
645,646,18.0,423.94,Female,Berlin,Basic,77.0,2021-10-07,user645@example.com,+1-555-1991,NaN,Poor,D03,SAVE20
670,671,17.0,304.01,Male,New York,Basic,99.0,2021-11-01,user670@example.com,+1-555-7374,NaN,Good,D03,NaN

In [445]:
genderNullRows = dataset[dataset["Gender"].isnull()].index.tolist
genderNullRows

<bound method IndexOpsMixin.tolist of Index([ 61, 113, 130, 141, 145, 179, 237, 293, 332, 367, 372, 382, 459, 480,
       514, 558, 574, 606, 617, 621, 633, 658, 746],
      dtype='int64')>

In [446]:
IsActiveNullRows = dataset[dataset["IsActive"].isnull()].index.tolist
IsActiveNullRows

<bound method IndexOpsMixin.tolist of Index([ 24,  31,  38,  67,  70, 114, 152, 209, 301, 316, 372, 374, 431, 489,
       524, 526, 539, 545, 610, 645, 670],
      dtype='int64')>

### Adding missing values in categorical data

In [447]:
dataset["Gender"].mode()[0]

'Female'

In [448]:
dataset["Gender"] = dataset["Gender"].fillna(dataset["Gender"].mode()[0])

In [449]:
dataset["Gender"].isnull().sum()

np.int64(0)

In [450]:
dataset["IsActive"].mode()[0]

'False'

In [451]:
dataset["IsActive"] = dataset["IsActive"].fillna(dataset["IsActive"].mode()[0])

In [452]:
dataset["IsActive"].isnull().sum()

np.int64(0)

# Encoding the IsActive and Gender columns

In [453]:
en_data = dataset[["Gender", "IsActive"]]
en_data

     Gender IsActive
0    Female     True
1    Female    False
2    Female    False
3      Male     True
4      Male    False
..      ...      ...
756    Male     True
757    Male    False
758  Female     True
759    Male     True
760  Female    False

[761 rows x 2 columns]

In [454]:
pd.get_dummies(en_data)

     Gender_Female  Gender_Male  IsActive_False  IsActive_True
0             True        False           False           True
1             True        False            True          False
2             True        False            True          False
3            False         True           False           True
4            False         True            True          False
..             ...          ...             ...            ...
756          False         True           False           True
757          False         True            True          False
758           True        False           False           True
759          False         True           False           True
760           True        False            True          False

[761 rows x 4 columns]

In [455]:
pd.get_dummies(en_data).info()

<class 'pandas.DataFrame'>
RangeIndex: 761 entries, 0 to 760
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Gender_Female   761 non-null    bool
 1   Gender_Male     761 non-null    bool
 2   IsActive_False  761 non-null    bool
 3   IsActive_True   761 non-null    bool
dtypes: bool(4)
memory usage: 3.1 KB

In [456]:
pd.get_dummies(en_data).columns.tolist()

['Gender_Female', 'Gender_Male', 'IsActive_False', 'IsActive_True']

## One hot encoding

In [457]:
from sklearn.preprocessing import OneHotEncoder

In [458]:
ohe = OneHotEncoder()
ohe.fit_transform(en_data).toarray()

array([[1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       ...,
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]], shape=(761, 4))

In [459]:
ar = ohe.fit_transform(en_data).toarray()
pd.DataFrame(ar, columns = [pd.get_dummies(en_data).columns.tolist()])

    Gender_Female Gender_Male IsActive_False IsActive_True
0             1.0         0.0            0.0           1.0
1             1.0         0.0            1.0           0.0
2             1.0         0.0            1.0           0.0
3             0.0         1.0            0.0           1.0
4             0.0         1.0            1.0           0.0
..            ...         ...            ...           ...
756           0.0         1.0            0.0           1.0
757           0.0         1.0            1.0           0.0
758           1.0         0.0            0.0           1.0
759           0.0         1.0            0.0           1.0
760           1.0         0.0            1.0           0.0

[761 rows x 4 columns]

### Removing first column for reducing number of columns and avoiding dummy variable trap (Multicollinearity)

In [460]:
ohe1 = OneHotEncoder(drop="first")
ohe1.fit_transform(en_data).toarray()
ar1 = ohe1.fit_transform(en_data).toarray()
pd.DataFrame(ar1, columns = ["Gender_Male","IsActive_True"])

     Gender_Male  IsActive_True
0            0.0            1.0
1            0.0            0.0
2            0.0            0.0
3            1.0            1.0
4            1.0            0.0
..           ...            ...
756          1.0            1.0
757          1.0            0.0
758          0.0            1.0
759          1.0            1.0
760          0.0            0.0

[761 rows x 2 columns]

### Integrating the new columns with the original dataset

In [461]:
# 1. Create the DataFrame from your One-Hot array
encoded_df = pd.DataFrame(ar1, columns=["Gender_Male", "IsActive_True"])

In [462]:
# 2. Combine with the original dataset
# axis=1 means 'add columns.'
dataset = pd.concat([dataset, encoded_df], axis=1)

In [463]:
# 3. Drop the original messy columns (Categorical columns are no longer needed)
dataset = dataset.drop(["Gender", "IsActive"], axis=1)

In [464]:
# Verify
dataset.head(5)

,PassengerId,Age,Fare,City,Subscription,Score,JoinDate,Email,Phone,Remarks,DeptCode,DiscountCode,Gender_Male,IsActive_True
0,1,52.0,104.22,Tokyo,Free,55.0,2020-01-01,NaN,+1-555-8540,Good,D04,NaN,0.0,1.0
1,2,15.0,30.03,London,Premium,82.0,2020-01-02,user1@example.com,+1-555-6340,Average,D04,NaN,0.0,0.0
2,3,72.0,92.78,New York,Basic,90.0,2020-01-03,user2@example.com,+1-555-3474,Poor,D02,SAVE10,0.0,0.0
3,4,61.0,146.51,London,Basic,87.0,2020-01-04,user3@example.com,+1-555-9521,Average,D04,WELCOME50,1.0,1.0
4,5,21.0,96.74,Tokyo,Basic,73.0,2020-01-05,user4@example.com,+1-555-1242,Unknown,D01,NaN,1.0,0.0

# Encoding the Subscription column

### Cleaning column before encoding

In [465]:
dataset['Subscription'].isnull().sum()

np.int64(26)

In [466]:
dataset['Subscription'] = dataset['Subscription'].fillna("FREE")

In [467]:
dataset['Subscription'].isnull().sum()

np.int64(0)

In [468]:
Subscription_map = {
    'Premium': 'PREMIUM',
    'Basic': 'BASIC',
    'none': 'FREE',
    'Free': 'FREE',
    'NONE': 'FREE'
}

In [469]:
dataset['Subscription'] = dataset['Subscription'].replace(Subscription_map)
dataset['Subscription'].unique()

<StringArray>
['FREE', 'PREMIUM', 'BASIC']
Length: 3, dtype: str

## Label Encoding vs Map vs Ordinal Encoding

In [2]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

In [471]:
le = LabelEncoder()
ar2 = le.fit_transform(dataset["Subscription"])

In [472]:
dfNew = pd.DataFrame()
dfNew["en_Subscription"]=pd.DataFrame(ar2)
dfNew["en_Subscription"].unique()

array([1, 2, 0])

In [473]:
dataset["Subscription"].unique()

<StringArray>
['FREE', 'PREMIUM', 'BASIC']
Length: 3, dtype: str

In [474]:
dataset["en_Subscription"] = ar2
dataset

,PassengerId,Age,Fare,City,Subscription,Score,JoinDate,Email,Phone,Remarks,DeptCode,DiscountCode,Gender_Male,IsActive_True,en_Subscription
0,1,52.0,104.22,Tokyo,FREE,55.0,2020-01-01,NaN,+1-555-8540,Good,D04,NaN,0.0,1.0,1
1,2,15.0,30.03,London,PREMIUM,82.0,2020-01-02,user1@example.com,+1-555-6340,Average,D04,NaN,0.0,0.0,2
2,3,72.0,92.78,New York,BASIC,90.0,2020-01-03,user2@example.com,+1-555-3474,Poor,D02,SAVE10,0.0,0.0,0
3,4,61.0,146.51,London,BASIC,87.0,2020-01-04,user3@example.com,+1-555-9521,Average,D04,WELCOME50,1.0,1.0,0
4,5,21.0,96.74,Tokyo,BASIC,73.0,2020-01-05,user4@example.com,+1-555-1242,Unknown,D01,NaN,1.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
756,757,60.0,67.70,New York,BASIC,70.0,2020-12-06,user340@example.com,+1-555-2234,ok,D02,NaN,1.0,1.0,0
757,758,57.0,450.79,New York,BASIC,82.0,2020-05-27,user147@example.com,+1-555-8248,ok,D03,NaN,1.0,0.0,0
758,759,9.0,320.40,Paris,PREMIUM,58.0,2020-11-26,user330@example.com,+1-555-3250,ok,D03,SAVE10,0.0,1.0,2
759,760,51.0,229.23,Paris,BASIC,61.0,2020-02-07,user37@example.com,+1-555-4198,Average,D04,NaN,1.0,1.0,0
760,761,19.0,337.36,Tokyo,FREE,59.0,2020-10-23,user296@example.com,+1-555-2459,Unknown,D01,SAVE20,0.0,0.0,1

In [475]:
dataset["en_Subscription"].unique()

array([1, 2, 0])

In [476]:
dataset[["Subscription", "en_Subscription"]].head(3)

  Subscription  en_Subscription
0         FREE                1
1      PREMIUM                2
2        BASIC                0

### The problem with the above "Label Encoder" methodology
The above code should work perfectly for converting your Subscription column into unique integers, but there is one major catch with LabelEncoder.

⚠️ The Problem: Randomized Order
LabelEncoder assigns numbers in alphabetical order, not by the actual rank of the subscription.

In your Subscription column:

Basic → 0
Free → 1
Premium → 2

Why this is bad for ML: Your model will think Free (1) is "between" Basic (0) and Premium (2), which makes no mathematical sense!

✅ The Better Way: **OrdinalEncoder (or .map)**
For ordered data like Subscription, you should manually specify the rank so the numbers reflect the real value.


🧠 Why use .map over LabelEncoder?
Control: You choose exactly what Free and Premium mean.
Accuracy: It prevents your machine learning model from learning fake relationships.
Handling NaNs: LabelEncoder will crash if it finds a NaN, but .map lets you easily fill them with a placeholder like -1.

### Map way

In [477]:
# 1. Define the logical order
sub_order = {'FREE': 0, 'BASIC': 1, 'PREMIUM': 2}
sub_order

{'FREE': 0, 'BASIC': 1, 'PREMIUM': 2}

In [478]:
# 2. Use a map to assign the exact ranks
dataset['Subscription_map_en'] = dataset['Subscription'].map(sub_order)

In [479]:
# 3. Handle NaNs (if any remain)
dataset['Subscription_map_en'] = dataset['Subscription_map_en'].fillna(-1).astype(int)

In [480]:
dataset[['Subscription', 'Subscription_map_en']].head(3)

  Subscription  Subscription_map_en
0         FREE                    0
1      PREMIUM                    2
2        BASIC                    1

In [481]:
dataset.head(3)

,PassengerId,Age,Fare,City,Subscription,Score,JoinDate,Email,Phone,Remarks,DeptCode,DiscountCode,Gender_Male,IsActive_True,en_Subscription,Subscription_map_en
0,1,52.0,104.22,Tokyo,FREE,55.0,2020-01-01,NaN,+1-555-8540,Good,D04,NaN,0.0,1.0,1,0
1,2,15.0,30.03,London,PREMIUM,82.0,2020-01-02,user1@example.com,+1-555-6340,Average,D04,NaN,0.0,0.0,2,2
2,3,72.0,92.78,New York,BASIC,90.0,2020-01-03,user2@example.com,+1-555-3474,Poor,D02,SAVE10,0.0,0.0,0,1

### Ordinal Encoder Way

In [482]:
dataset['Subscription'].mode()[0]

'BASIC'

In [483]:
# 1. First, handle any remaining NaNs (OrdinalEncoder fails on NaNs by default)
dataset['Subscription'] = dataset['Subscription'].fillna('FREE')

In [5]:
# 2. Define the logical order in a list of lists
# The first element in the list will be 0, the second 1, etc.
sub_categories = [['FREE', 'BASIC', 'PREMIUM']]
sub_categories

[['FREE', 'BASIC', 'PREMIUM']]

In [6]:
# 3. Initialize the OrdinalEncoder with your categories
oe = OrdinalEncoder(categories=sub_categories)
oe

OrdinalEncoder(categories=[['FREE', 'BASIC', 'PREMIUM']])

In [7]:
# 4. Fit and transform the column
# Note: It requires a 2D array, so we use double brackets [[...]]
dataset['Subscription_Ord_Encoded'] = oe.fit_transform(dataset[['Subscription']])

NameError: name 'dataset' is not defined

In [487]:
dataset[['Subscription', 'Subscription_Ord_Encoded']].head(3)

  Subscription  Subscription_Ord_Encoded
0         FREE                       0.0
1      PREMIUM                       2.0
2        BASIC                       1.0

In [488]:
dataset.head(3)

,PassengerId,Age,Fare,City,Subscription,Score,JoinDate,Email,Phone,Remarks,DeptCode,DiscountCode,Gender_Male,IsActive_True,en_Subscription,Subscription_map_en,Subscription_Ord_Encoded
0,1,52.0,104.22,Tokyo,FREE,55.0,2020-01-01,NaN,+1-555-8540,Good,D04,NaN,0.0,1.0,1,0,0.0
1,2,15.0,30.03,London,PREMIUM,82.0,2020-01-02,user1@example.com,+1-555-6340,Average,D04,NaN,0.0,0.0,2,2,2.0
2,3,72.0,92.78,New York,BASIC,90.0,2020-01-03,user2@example.com,+1-555-3474,Poor,D02,SAVE10,0.0,0.0,0,1,1.0

In [489]:
dataset.drop(columns=["en_Subscription", "Subscription"], inplace=True)
dataset.head(3)

,PassengerId,Age,Fare,City,Score,JoinDate,Email,Phone,Remarks,DeptCode,DiscountCode,Gender_Male,IsActive_True,Subscription_map_en,Subscription_Ord_Encoded
0,1,52.0,104.22,Tokyo,55.0,2020-01-01,NaN,+1-555-8540,Good,D04,NaN,0.0,1.0,0,0.0
1,2,15.0,30.03,London,82.0,2020-01-02,user1@example.com,+1-555-6340,Average,D04,NaN,0.0,0.0,2,2.0
2,3,72.0,92.78,New York,90.0,2020-01-03,user2@example.com,+1-555-3474,Poor,D02,SAVE10,0.0,0.0,1,1.0